name: GitHub Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  Test:
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Testing
        run: echo "Testing..."
  Load-Test:
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: Load-Test
    steps:
      - name: Testing
        run: |
          echo "Testing..."
          sleep 15
  Production:
    needs: [Test, Load-Test]
    if: github.event.inputs.environment == 'Production'
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deployment Step 1
        run: |
          echo "Step 1 deploying..."
          sleep 10
      - name: Deployment Step 2
        run: |
          echo "Step 2 deploying..."
          sleep 10
      - name: Deployment Step 3
        run: |
          echo "Step 3 deploying..."
          sleep 10
      - name: Deployment Step 4
        run: |
          echo "Step 4 deploying..."
          sleep 10
      - name: Deployment Step 5
        run: |
          echo "Step 5 deploying..."
          sleep 10
